/**
 *
/**
 * @author Rohit Ahuja
 * rohitahuja@email.com
 * 9893075987
 */


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CoursewiseSubjects.java
 *
 * Created on Apr 18, 2009, 5:01:31 PM
 */
package com.vedisoft.sis;

import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows XP
 */
public class CoursewiseSubjects extends javax.swing.JPanel {

    /** Creates new form CoursewiseSubjects */
    public CoursewiseSubjects() {
        initComponents();
        Subjects p = new Subjects();
        Vector rows = p.getRecordsTwo();
        Vector columns = p.getColumnsOne();
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.setDataVector(rows, columns);
    }

    public static void main(String[] args) {
        JFrame f = new JFrame("Coursewise Subjects Form");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setContentPane(new CoursewiseSubjects());
        f.setBounds(10, 10, 500, 500);
        f.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
/**
* Vedisoft : Java - Module 1 "Desktop Technologies"
*
*
*   Vedisoft Software & Education Services Pvt. Ltd.
*   Plot No. 275, Zone II, M.P. Nagar,
*   Bhopal.
*   Phone : 0755 - 4076207, 4076208
*   Email : contact@vedisoft.com
*   Web : www.vedisoft.com
*/