
package com.vedisoft.sis;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class CoursePanel extends javax.swing.JPanel {

    /** Creates new form CoursePanel */
    public CoursePanel() {
        initComponents();
        c = new Course();
        int num = c.getTotal();
        if (num >= 1) {
            cur = 1;
            tot = num;
            c = c.getRecord(1);
            show(c);
        }
        updateStatus();
    }

    public void updateStatus() {
        jLabel1.setText("Row " + cur + " of " + tot);
    }

    public void show(Course c) {
        jTextField1.setText(c.getCoursename());
        jTextField2.setText(c.getCoursetype());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setFont(new java.awt.Font("Courier New", 1, 18));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Courses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 3, 18))); // NOI18N
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 18));
        jLabel3.setText("Name ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 100, 140, 23);

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 18));
        jLabel4.setText("Type");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 170, 130, 23);

        jTextField1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);
        jTextField1.setBounds(280, 90, 160, 30);

        jTextField2.setFont(new java.awt.Font("Verdana", 3, 18));
        jPanel3.add(jTextField2);
        jTextField2.setBounds(290, 160, 160, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(20, 10, 530, 270);

        jButton1.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(30, 290, 90, 40);

        jButton2.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(120, 290, 120, 40);

        jButton3.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(240, 290, 130, 40);

        jButton4.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton4.setText("First");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(30, 330, 100, 40);

        jButton5.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton5.setText("Next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(120, 330, 120, 40);

        jButton6.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton6.setText("Previous");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(240, 330, 130, 40);

        jButton7.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton7.setText("Save");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(370, 290, 110, 40);

        jButton8.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton8.setText("Last");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(370, 330, 110, 40);

        jButton9.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton9.setText("Show Subjects");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(30, 370, 450, 50);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Row : 1 of 10");
        jPanel1.add(jLabel1);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 450, 628, 33);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (cur == tot) {
            JOptionPane.showMessageDialog(this, "Already on Last Record");
            return;
        } else {
            c = c.getRecord(tot);
            show(c);
            cur = tot;
            updateStatus();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jButton7.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        c.setCoursename(jTextField1.getText());
        c.setCoursetype(jTextField2.getText());
        boolean b = c.update();
        if (b) {
            JOptionPane.showMessageDialog(this, "Record Updation Successful.");
        } else {
            JOptionPane.showMessageDialog(this, "Record Updation Failure.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean b = c.delete();
        if (b) {
            tot -= 1;
            cur -= 1;
            JOptionPane.showMessageDialog(this, "Record Deletion Successful.");
            if (cur == 0 && tot == 0) {
                jTextField1.setText("");
                jTextField2.setText("");
            } else if (cur >= 1) {
                c = c.getRecord(cur);
                show(c);
                updateStatus();
            } else {
                cur = tot;
                c = c.getRecord(cur);
                show(c);
                updateStatus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Record Deletion Failure.");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        c.setCoursename(jTextField1.getText());
        c.setCoursetype(jTextField2.getText());
        boolean b = c.add();
        if (b) {
            tot += 1;
            cur = tot;
            c = c.getRecord(cur);
            show(c);
            updateStatus();
            jButton7.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Record Insertion Successful.");
        } else {
            JOptionPane.showMessageDialog(this, "Record Insertion Failure.");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (cur == 1) {
            JOptionPane.showMessageDialog(this, "Already on First Record");
            return;
        }
        if (tot >= 1) {
            c = c.getRecord(1);
            show(c);
            cur = 1;
            updateStatus();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (cur == tot) {
            JOptionPane.showMessageDialog(this, "Already on Last Record");
            return;
        } else {
            cur += 1;
            c = c.getRecord(cur);
            show(c);
            updateStatus();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (cur == 1) {
            JOptionPane.showMessageDialog(this, "Already on First Record");
            return;
        } else {
            cur -= 1;
            c = c.getRecord(cur);
            show(c);
            updateStatus();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        JFrame f = new JFrame("Coursewise Subjects Form");
        f.setContentPane(new CourseSubjectsOne(c.getCourseid(), c.getCoursename()));
        f.setBounds(10, 10, 500, 500);
        f.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public static void main(String[] args) {
        JFrame f = new JFrame("Course Form");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setContentPane(new CoursePanel());
        f.setBounds(10, 10, 500, 500);
        f.setVisible(true);
    }
    Course c;
    int cur = 0;
    int tot = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
