package com.vedisoft.sis;

import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class MarksPanel extends javax.swing.JPanel {

    /** Creates new form MarksPanel */
    public MarksPanel() {
        m = new Marks();
        studentids = m.getStudedentids();
        students = m.getStudents();
        subjectids = m.getSubjectids();
        subjects = m.getSubjects();
        initComponents();
        int num = m.getTotal();
        if (num >= 1) {
            cur = 1;
            tot = num;
            m = m.getRecord(1);
            show(m);
        }
        updateStatus();
    }

    public void updateStatus() {
        jLabel1.setText("Row " + cur + " of " + tot);
    }

    public void show(Marks p) {
        jComboBox1.setSelectedIndex(p.getSubjectid());
        jComboBox2.setSelectedIndex(p.getStudentid());
        jTextField1.setText("" + p.getMarks());
    }

    public static void main(String[] args) {
        JFrame f = new JFrame("Subjects Form");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setContentPane(new MarksPanel());
        f.setBounds(10, 10, 500, 500);
        f.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox(subjects);
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox(students);
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Row : 1 of 10");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marks Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 3, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 18));
        jLabel2.setText("Subject");

        jComboBox1.setFont(new java.awt.Font("Verdana", 3, 18));

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 18));
        jLabel3.setText("Student");

        jComboBox2.setFont(new java.awt.Font("Verdana", 3, 18));

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 18));
        jLabel4.setText("Marks");

        jTextField1.setFont(new java.awt.Font("Verdana", 3, 18));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19))
                    .addComponent(jLabel3))
                .addGap(117, 117, 117)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox2, 0, 188, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 10, 510, 210);

        jButton1.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(40, 260, 120, 50);

        jButton2.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(160, 260, 120, 50);

        jButton3.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(280, 260, 120, 50);

        jButton4.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton4.setText("Save");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(400, 260, 110, 50);

        jButton5.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton5.setText("First");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(40, 310, 120, 50);

        jButton6.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton6.setText("Next");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(160, 310, 110, 50);

        jButton7.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton7.setText("Previous");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(270, 310, 130, 50);

        jButton8.setFont(new java.awt.Font("Verdana", 3, 18));
        jButton8.setText("Last");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(400, 310, 110, 50);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        m.setSubjectid(jComboBox1.getSelectedIndex());
        m.setStudentid(jComboBox2.getSelectedIndex());
        m.setMarks(Integer.parseInt(jTextField1.getText()));
        boolean b = m.add();
        if (b) {
            tot += 1;
            cur = tot;
            m = m.getRecord(cur);
            show(m);
            updateStatus();
            jButton4.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Record Insertion Successful.");
        } else {
            JOptionPane.showMessageDialog(this, "Record Insertion Failure.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        m.setSubjectid(jComboBox1.getSelectedIndex());
        m.setStudentid(jComboBox2.getSelectedIndex());
        m.setMarks(Integer.parseInt(jTextField1.getText()));
        boolean b = m.update();
        if (b) {
            JOptionPane.showMessageDialog(this, "Record Updation Successful.");
        } else {
            JOptionPane.showMessageDialog(this, "Record Updation Failure.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean b = m.delete();
        if (b) {
            tot -= 1;
            cur -= 1;
            JOptionPane.showMessageDialog(this, "Record Deletion Successful.");
            if (cur == 0 && tot == 0) {
                jComboBox1.setSelectedIndex(-1);
                jComboBox2.setSelectedIndex(-1);
                jTextField1.setText("");

            } else if (cur >= 1) {
                m = m.getRecord(cur);
                show(m);
                updateStatus();
            } else {
                cur = tot;
                m = m.getRecord(cur);
                show(m);
                updateStatus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Record Deletion Failure.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (cur == 1) {
            JOptionPane.showMessageDialog(this, "Already on First Record");
            return;
        }
        if (tot >= 1) {
            m = m.getRecord(1);
            show(m);
            cur = 1;
            updateStatus();

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (cur == tot) {
            JOptionPane.showMessageDialog(this, "Already on Last Record");
            return;
        } else {
            cur += 1;
            m = m.getRecord(cur);
            show(m);
            updateStatus();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (cur == 1) {
            JOptionPane.showMessageDialog(this, "Already on First Record");
            return;
        } else {
            cur -= 1;
            m = m.getRecord(cur);
            show(m);
            updateStatus();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (cur == tot) {
            JOptionPane.showMessageDialog(this, "Already on Last Record");
            return;
        } else {
            m = m.getRecord(tot);
            show(m);
            cur = tot;
            updateStatus();
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    Marks m;
    int cur = 0;
    int tot = 0;
    Vector subjectids;
    Vector subjects;
    Vector studentids;
    Vector students;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
